apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-cluster
  namespace: default
spec:
  serviceName: mysql  # 一定要指定StatefulSet的serviceName
  selector:
    matchLabels:
      app: mysql 
  replicas: 2 # 默认的负载均衡，一个Service，一会连这个Pod，一会连那个Pod
  template:
    metadata:
      labels:
        app: mysql # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10 # 平滑关机
      containers:
      - name: mysql
        image: mysql:8.0.25
        securityContext:  ## 指定安全上下文
          runAsUser: 1000
          runAsGroup: 1000
        ports:
        - containerPort: 3306
          name: mysql-port
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_DATABASE
          value: "db_test"
        volumeMounts:
        - name: mysql-cnf
          mountPath: /etc/mysql/conf.d
        - name: mysql-data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-cnf
    spec:
      storageClassName: "managed-nfs-storage"
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: mysql-data
    spec:
      storageClassName: "managed-nfs-storage"
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: default
spec:
  selector:
    app: mysql
  type: NodePort 
  # type: ClusterIP
  # clusterIP: None  ## 没有集群ip，只能通过内部的dns访问 mysql-cluster-0.mysql.default
  ports:
  - name: mysql-port
    port: 3306 ## service端口
    targetPort:  3306 ## pod端口
    protocol: TCP


### 目前部署的这两个mysql，自己连进去操作才能主从同步  ###

# mysql的负载均衡得至少部署两个Service网络，一个连主，一个连从
# 【给外部NodePort两个Service网络（考虑一下Ingress），内部两个Head-less Service网络（方便集群内部通信）】