apiVersion: v1
kind: Service
metadata:
  name: svc-session-test
  namespace: default
spec:
  selector:
    app: canary-nginx
  type: NodePort
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80