# 生产环境肯定不放在代码中，这儿是为了方便
# 提前部署进去

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ware
  namespace: default
  labels:
    app: ware
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ware
  template:
    metadata:
      labels:
        app: ware
    spec:
#      serviceAccountName: myapp-sa
      containers:
        - name: ware
          image: crpi-co509r5gdyecg5t2.cn-hangzhou.personal.cr.aliyuncs.com/lpruoyu/ware:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: ware-service
  namespace: default
  labels:
    app: ware
spec:
  selector:
    app: ware
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP