# 打污点
# kubectl taint nodes  k8s-node1 haha=hehe:NoSchedule
# kubectl taint nodes  k8s-node2 haha=666:NoSchedule

# 去除污点
# kubectl taint nodes  k8s-node1 haha=hehe:NoSchedule-
# kubectl taint nodes  k8s-node2 haha-


# kubectl taint nodes k8s-ha-master2 node-role.kubernetes.io/master=:NoSchedule
# kubectl taint nodes k8s-ha-master2 node-role.kubernetes.io/master=:NoExecute-

apiVersion: v1
kind: Pod
metadata:
  name: "pod-taint-02"
  namespace: default
  labels:
    app: "pod-taint-02"
spec:
  containers:
  - name: pod-taint-02
    image: "busybox"
    command: ["sleep","3600"]
  tolerations: ## 容忍
  - key: "haha"
    # operator: "Equal"
    # value: "666"
    effect: "NoSchedule"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  taint-haha
  namespace: default
  labels:
    app:  taint-haha
spec:
  selector:
    matchLabels:
      app: taint-haha
  replicas: 3
  template:
    metadata:
      labels:
        app:  taint-haha
    spec:
      # initContainers:
      # - name:  init-01 #request-cpu: 300m
      #   image:  "busybox"
      #   command: ["sleep","3600"] 
      # - name:  init-02 #request-cpu: 100m
      #   image:  "busybox"
      #   command: ["sleep","3600"] 
      containers: 
      - name:  taint-haha  #request-cpu: 200m
        image:  "busybox"
        command: ["sleep","3600"] 
      # - name:  taint-hehe  #request-cpu: 100m
      #   image:  "busybox"
      #   command: ["sleep","3600"] 
      tolerations: ## 容忍
      - key: "haha"
        operator: "Exists"
        effect: "NoSchedule"
    