apiVersion: v1
kind: Pod
metadata:
  name: "pod-nfs-demo"
  namespace: default
  labels:
    app: "pod-nfs-demo"
spec:
  containers:
  - name: pod-nfs-demo
    image: "nginx"
    volumeMounts:
    - name: localtime
      mountPath: /etc/localtime
    - name: html
      mountPath: /usr/share/nginx/html
  volumes:
    - name: localtime
      hostPath:
        path: /usr/share/zoneinfo/Asia/Shanghai
    - name: html
      nfs:
        path: /nfs/data/nginx #/nfs/data/nginx这个文件夹得准备好  #1000G
        server: 192.168.10.137 #自己的nfs服务器地址
