apiVersion: v1
kind: Pod
metadata:
  name: "pod-secret-volume"
  namespace: default
  labels:
    app: "pod-secret-volume"
spec:
  volumes: ## 指定挂载详情
  - name: app
    secret: 
      # defaultMode: 0777 ### 修改默认的权限模式
      secretName: dev-db-secret  ### secret里面所有的key全部挂出来
      items:
      - key: password  ## dev-db-secret里面的password这个key的内容挂出来
        path: pwd.md ### 默认secret里面数据的key是作为文件名的。 path就是相当于我们自己指定一个文件名
  containers:
  - name: pod-secret-volume
    image: "busybox"
    command: ["/bin/sh","-c","sleep 3600"]  ## echo $My_USR
    volumeMounts:
    - name: app
      mountPath: /app  ## 容器内的app文件夹是dev-db-secret的内容
      readOnly: false 


# 反向更新？【上面这样写，目前没用】