kind: Pod
apiVersion: v1
metadata:
  name: my-life
  namespace: hello
  labels:
     aa: bb
     bb: dd
spec:  
  containers:  
  - image: nginx  
    name: nginx  
    # 探针 ==类似== 健康检查机制 ==========》合理应用好探针，可以实现零宕机
    startupProbe: #启动探针 。kubelet看当前容器是否启动了
      httpGet:
      tcpSocket:
      exec:
    livenessProbe: #存活探针 。告诉kubelet容器活着没，如果容器死了，kubelet就会重启该pod
      httpGet:
      tcpSocket:
      exec:
    readinessProbe: #就绪探针 。 告诉kubelet当前容器能否对外提供服务。如果能，k8s的负载均衡网络才会发流量给你
      httpGet:
      tcpSocket:
      exec:

