apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-12m-recycle
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Recycle  
  storageClassName: my-nfs-storage
  capacity:
    storage: 12m
  accessModes:
    - ReadWriteOnce 
  nfs:  
    server: 192.168.10.137 
    path: /nfs/data/haha
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-12-recycle
  namespace: default
  labels:
    app: pv-12-recycle
spec:
  storageClassName: my-nfs-storage 
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 12m
---
apiVersion: v1
kind: Pod
metadata:
  name: "nginx-pvc"
  namespace: default
  labels:
    app: "nginx-pvc"
spec:
  containers:
  - name: nginx-pvc
    image: "nginx"
    ports:
    - containerPort:  80
      name:  http
    volumeMounts:
    - name: localtime
      mountPath: /etc/localtime
    - name: html
      mountPath: /usr/share/nginx/html
  volumes:
    - name: localtime
      hostPath:
        path: /usr/share/zoneinfo/Asia/Shanghai
    - name: html
      persistentVolumeClaim:
         claimName:  pv-12-recycle