
# echo -n 'admin' > username.txt

# echo -n '1f2d1e2e67df' > password.txt

# kubectl create secret generic filetest666-secret \
#   --from-file=username.txt \
#   --from-file=password.txt


# [root@k8s-master ~]# kubectl get secrets filetest666-secret -oyaml
# apiVersion: v1
# data:
#   password.txt: MWYyZDFlMmU2N2Rm
#   username.txt: YWRtaW4=
# kind: Secret
# metadata:
#   creationTimestamp: "2026-02-27T07:08:39Z"
#   name: filetest666-secret
#   namespace: default
#   resourceVersion: "425373"
#   uid: 3ba5f198-2251-4b9d-ac0d-8a11d37e91c4
# type: Opaque



apiVersion: v1
kind: Pod
metadata:
  name: "pod-secret-volume"
  namespace: default
  labels:
    app: "pod-secret-volume"
spec:
  volumes: 
  - name: app
    secret: 
      secretName: filetest666-secret
      items:
      - key: username.txt
        path: username-new-name.txt
  containers:
  - name: pod-secret-volume
    image: "busybox"
    command: ["/bin/sh","-c","sleep 3600"]
    volumeMounts:
    - name: app
      mountPath: /app  


# [root@k8s-master ~]# kubectl exec -it pod-secret-volume   --  /bin/sh
# / # ls
# app    bin    dev    etc    home   lib    lib64  proc   root   sys    tmp    usr    var
# / # cd app
# /app # ls
# username-new-name.txt
# /app # cat username-new-name.txt 
# admin/app # 
