#挂载使用secret可以热更新【修改secret看效果】kubectl edit secrets  dev-db-secret
apiVersion: v1
kind: Pod
metadata:
  name: "pod-secret-volume-1"
  namespace: default
  labels:
    app: "pod-secret-volume-1"
spec:
  volumes: 
  - name: app
    secret: 
      secretName: dev-db-secret # secret中的所有key-value会被挂出去；其中key作为文件名，value作为文件值
  containers:
  - name: pod-secret-volume-1
    image: "busybox"
    command: ["/bin/sh","-c","sleep 3600"]
    volumeMounts:
    - name: app
      mountPath: /app

#创建secret
# kubectl create secret generic dev-db-secret \
#   --from-literal=username=devuser \
#   --from-literal=password='S!B\*d$zDsb='
#查看dev-db-secret
# [root@k8s-master ~]# kubectl get secrets dev-db-secret -oyaml
# apiVersion: v1
# data:
#   password: UyFCXCpkJHpEc2I9
#   username: ZGV2dXNlcg==
# kind: Secret
# metadata:
#   creationTimestamp: "2026-02-27T04:31:37Z"
#   name: dev-db-secret
#   namespace: default
#   resourceVersion: "410668"
#   uid: d077592b-2b0f-4788-94c4-5c08369b44af
# type: Opaque
#挂载后容器内结果：
# [root@k8s-master ~]# kubectl exec -it pod-secret-volume-1 -- /bin/sh
# / # ls
# app    bin    dev    etc    home   lib    lib64  proc   root   sys    tmp    usr    var
# / # cd app && ls
# password  username
# /app # cat password && cat username
# S!B\*d$zDsb=devuser 