apiVersion: v1
kind: ServiceAccount
metadata:
  name: lfy
  namespace: default
# kubectl describe serviceaccount lfy # kubectl get secrets #会发现创建的账号会自动关联一个secret

---
#  写角色
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default  
  name: namespace-reader 
rules:
- apiGroups: [""] 
  resources: ["namespaces"] 
  verbs: ["get", "watch", "list"] 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ns-reader 
rules: 
- apiGroups: [""] 
  resources: ["namespaces"]
  verbs: ["get", "watch", "list"] 

---
## 编写角色和账号的绑定关系
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: all-global
subjects: 
- kind: ServiceAccount
  name: lfy
  namespace: default
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: ns-reader
  # name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
#kubectl get clusterrolebinding | grep cluster-admin #查看